# Root terragrunt.hcl — loaded by all child configs via find_in_parent_folders()
#
# Directory hierarchy: <account>/<region>/<environment>/<module>/terragrunt.hcl
# Three config layers resolved via find_in_parent_folders():
#   account.hcl  → tenancy identity, namespace, OCI CLI profile
#   region.hcl   → OCI region
#   env.hcl      → environment name, project name

locals {
  # ── 3-layer config ──────────────────────────────────────────────────────────
  account_vars = read_terragrunt_config(find_in_parent_folders("account.hcl"))
  region_vars  = read_terragrunt_config(find_in_parent_folders("region.hcl"))
  env_vars     = read_terragrunt_config(find_in_parent_folders("env.hcl"))

  # Account
  account_name        = local.account_vars.locals.account_name
  tenancy_ocid        = local.account_vars.locals.tenancy_ocid
  compartment_id      = local.account_vars.locals.compartment_id
  oci_namespace       = local.account_vars.locals.namespace
  config_file_profile = try(local.account_vars.locals.config_file_profile, "DEFAULT")

  # Region
  region = local.region_vars.locals.region

  # Environment
  env     = local.env_vars.locals.environment
  project = local.env_vars.locals.project

  # State bucket — scoped per account + project
  state_bucket = "tfstate-${local.account_name}-${local.project}"
}

# ── Remote State ──────────────────────────────────────────────────────────────
# Uses OCI Object Storage via its S3-compatible API.
# Prerequisites:
#   1. Create a Customer Secret Key in OCI Console (Identity → Users → Customer Secret Keys)
#   2. export AWS_ACCESS_KEY_ID=<customer-secret-key-id>
#   3. export AWS_SECRET_ACCESS_KEY=<customer-secret-key-secret>
#
# State key layout: <region>/<environment>/<module>/terraform.tfstate
# This ensures state isolation across accounts, regions, and environments.
remote_state {
  backend = "s3"

  config = {
    bucket = local.state_bucket
    key    = "${local.region}/${local.env}/${path_relative_to_include()}/terraform.tfstate"
    region = "us-east-1" # placeholder — OCI S3-compat ignores region

    endpoint                    = "https://${local.oci_namespace}.compat.objectstorage.${local.region}.oraclecloud.com"
    skip_credentials_validation = true
    skip_metadata_api_check     = true
    skip_region_validation      = true
    force_path_style            = true
  }

  generate = {
    path      = "backend.tf"
    if_exists = "overwrite_terragrunt"
  }
}

# ── Provider Generation ────────────────────────────────────────────────────────
# Generates provider_tg.tf with region and config_file_profile from account.hcl.
# Provider version constraints stay in each module's versions.tf.
#
# Authentication:
#   Each account.hcl defines a config_file_profile (e.g., "DEFAULT", "personal", "company").
#   These profiles must exist in ~/.oci/config.
#   Alternatively, set OCI_CLI_* env vars (profile is ignored when env vars are set).
generate "provider" {
  path      = "provider_tg.tf"
  if_exists = "overwrite_terragrunt"
  contents  = <<-EOT
    # Generated by Terragrunt — do not edit manually.
    # Provider version constraints live in the module's versions.tf.
    provider "oci" {
      region              = "${local.region}"
      config_file_profile = "${local.config_file_profile}"
    }
  EOT
}

# ── Shared inputs ─────────────────────────────────────────────────────────────
# Merged (deep) with _envcommon/*.hcl and per-environment terragrunt.hcl.
inputs = {
  project        = local.project
  environment    = local.env
  compartment_id = local.compartment_id
  tenancy_ocid   = local.tenancy_ocid
  freeform_tags = {
    Project     = local.project
    Environment = local.env
    Account     = local.account_name
    Region      = local.region
    ManagedBy   = "terraform"
  }
}
