# Root terragrunt.hcl — loaded by all child configs via find_in_parent_folders()

locals {
  # Parse env.hcl from the environment directory (development, production, etc.)
  env_vars = read_terragrunt_config(find_in_parent_folders("env.hcl"))

  env     = local.env_vars.locals.environment
  region  = local.env_vars.locals.region
  project = local.env_vars.locals.project

  # OCI Object Storage namespace for remote state — set via TF_VAR or env var
  # export TG_OCI_NAMESPACE=<your-namespace>
  oci_namespace = get_env("TG_OCI_NAMESPACE", "")

  # State bucket — one bucket, paths per module
  state_bucket = "terragrunt-state-${local.project}-${local.env}"
}

# ── Remote State ──────────────────────────────────────────────────────────────
# Uses OCI Object Storage via its S3-compatible API.
# Prerequisites:
#   1. Create a Customer Secret Key in OCI Console (Identity → Users → Customer Secret Keys)
#   2. export AWS_ACCESS_KEY_ID=<customer-secret-key-id>
#   3. export AWS_SECRET_ACCESS_KEY=<customer-secret-key-secret>
#   4. export TG_OCI_NAMESPACE=<object-storage-namespace>
remote_state {
  backend = "s3"

  config = {
    bucket = local.state_bucket
    key    = "${path_relative_to_include()}/terraform.tfstate"
    region = "us-east-1" # placeholder — OCI S3-compat ignores region

    endpoint                    = "https://${local.oci_namespace}.compat.objectstorage.${local.region}.oraclecloud.com"
    skip_credentials_validation = true
    skip_metadata_api_check     = true
    skip_region_validation      = true
    force_path_style            = true
  }

  generate = {
    path      = "backend.tf"
    if_exists = "overwrite_terragrunt"
  }
}

# ── Provider Generation ────────────────────────────────────────────────────────
# Generates provider_tg.tf (provider "oci" only; version pins stay in each module's versions.tf).
#
# Authentication — choose one:
#   Option A (recommended): Configure ~/.oci/config with [DEFAULT] profile
#     $ oci setup config
#   Option B: Environment variables
#     export OCI_CLI_TENANCY=<tenancy-ocid>
#     export OCI_CLI_USER=<user-ocid>
#     export OCI_CLI_FINGERPRINT=<api-key-fingerprint>
#     export OCI_CLI_KEY_FILE=~/.oci/oci_api_key.pem
#
# The `region` is resolved by Terragrunt from env.hcl at generation time, so
# the generated file contains the literal region string — no Terraform variables
# for provider auth are needed and no undeclared-variable errors can occur.
generate "provider" {
  path      = "provider_tg.tf"
  if_exists = "overwrite_terragrunt"
  contents  = <<-EOT
    # Generated by Terragrunt — do not edit manually.
    # Provider version constraints live in the module's versions.tf (single source of truth).
    provider "oci" {
      # Auth from ~/.oci/config [DEFAULT] profile or OCI_CLI_* env vars.
      region = "${local.region}"
    }
  EOT
}

# ── Shared inputs ─────────────────────────────────────────────────────────────
# Merged (deep) with _envcommon/*.hcl and per-environment terragrunt.hcl.
inputs = {
  project     = local.project
  environment = local.env
  freeform_tags = {
    Project     = local.project
    Environment = local.env
    ManagedBy   = "terraform"
  }
}
