include "root" {
  path   = find_in_parent_folders("root.hcl")
  expose = true
}

include "envcommon" {
  path           = "${dirname(find_in_parent_folders("root.hcl"))}/_envcommon/object-storage.hcl"
  expose         = true
  merge_strategy = "deep"
}

locals {
  account_vars = read_terragrunt_config(find_in_parent_folders("account.hcl"))
  env_vars     = read_terragrunt_config(find_in_parent_folders("env.hcl"))
  region_vars  = read_terragrunt_config(find_in_parent_folders("region.hcl"))
  account_name = local.account_vars.locals.account_name
  environment  = local.env_vars.locals.environment
  project      = local.env_vars.locals.project

  namespace_raw = trimspace(local.account_vars.locals.namespace)
  object_storage_namespace = (
    length(local.namespace_raw) > 0 &&
    lower(local.namespace_raw) != "replace_me" &&
    local.namespace_raw != "REPLACE_ME"
  ) ? local.namespace_raw : null

  # Map key for the state bucket = last path segment of get_terragrunt_dir() (e.g. .../object-storage -> object-storage).
  _tg_path_segments = compact(split("/", replace(get_terragrunt_dir(), "\\", "/")))
  tfstate_bucket_key = local._tg_path_segments[length(local._tg_path_segments) - 1]
  tfstate_bucket_name = "${local.project}-tfstate"

  # One-time import of an existing bucket: export TG_IMPORT_TFSTATE_BUCKET=true (needs namespace below).
  tg_import_tfstate_bucket = trimspace(lower(get_env("TG_IMPORT_TFSTATE_BUCKET", ""))) == "true"
  tg_import_composite_id = (
    local.tg_import_tfstate_bucket &&
    local.object_storage_namespace != null &&
    length(trimspace(local.object_storage_namespace)) > 0
  ) ? "n/${trimspace(local.object_storage_namespace)}/b/${local.tfstate_bucket_name}" : null

  # Stub only — cannot use two <<-EOT branches in one ternary (Terragrunt/HCL parse error).
  import_tf_stub = <<-EOT
# import.tf — generated by Terragrunt
#
# To emit a one-time Terraform 1.5+ import block for the tfstate bucket:
#   export TF_VAR_namespace="$(oci os ns get --query data --raw-output)"
#   export TG_IMPORT_TFSTATE_BUCKET=true
#   terragrunt plan
#
# Requires a real Object Storage namespace (same as module inputs). See object-storage/import.tf in the module.
EOT
}

# Generates import.tf (working dir). import branch uses format() + one heredoc — not two heredocs in a ternary.
generate "import_tf" {
  path      = "import.tf"
  if_exists = "overwrite_terragrunt"
  contents = local.tg_import_composite_id != null ? format(
    <<-EOT
# Generated by Terragrunt (TG_IMPORT_TFSTATE_BUCKET=true). Unset or set TG_IMPORT_TFSTATE_BUCKET=false after apply.
# Composite ID only — do not import by bucket OCID.

import {
  to = oci_objectstorage_bucket.this["%[1]s"]
  id = "%[2]s"
}
EOT
    ,
    local.tfstate_bucket_key,
    local.tg_import_composite_id,
  ) : local.import_tf_stub
}

inputs = {
  buckets = {
    (local.tfstate_bucket_key) = {
      name         = local.tfstate_bucket_name
      namespace    = local.object_storage_namespace
      access_type  = "NoPublicAccess"
      storage_tier = "Standard"
      versioning   = "Enabled"
    }
    // app-bucket = {
    //   name         = "oci-modules-${local.environment}-app-bucket"
    //   namespace    = null
    //   access_type  = "NoPublicAccess"
    //   storage_tier = "Standard"
    //   versioning   = "Disabled"
    // }
    // logs-bucket = {
    //   name         = "oci-modules-${local.environment}-logs-bucket"
    //   namespace    = null
    //   access_type  = "NoPublicAccess"
    //   storage_tier = "Standard"
    //   versioning   = "Disabled"
    // }
  }
}
